Dima review
KiK0S/3d-framework pull request #2
Opened 2021-05-24 18:56 UTC by KiK0S

У меня сломался прошлый пул (вернее, я его сломал). Дима, сори за пинг, я все равно сначала посмотрю то, что было там.

2021-05-25 15:56 UTC, DimaTrushin reviewed
Стало сильно лучше.
Убрать пустые файлы.
Добавить assert-ы на проверку прекондишинов и инвариантов, проверку корректности и допустимых значений параметров.

2021-05-25 15:56 UTC, DimaTrushin commented on .gitignore
> +*.pygstyle
пустая строка в конце.

2021-05-25 15:56 UTC, DimaTrushin commented on readme.md
> +                 <ul>
Что-то не то с разметкой

2021-05-25 15:56 UTC, DimaTrushin commented on src/application.cpp
> +    int fixed_coord = 0;
Это должна быть одна функция преобразования axe в int. Иначе получается нарушение уровня абстракции.

2021-05-25 15:56 UTC, DimaTrushin commented on src/application.cpp
> +    Matrix4d moving = Matrix4d::identity_matrix();
Вот тут строчки по построению матрицы движения, то надо выделить в отельную функцию.

2021-05-25 15:56 UTC, DimaTrushin commented on src/application.cpp
> +    int fixed_coord = 0;
Судя по всему логика у тебя такая
```cpp
int fixted_coord = axis_to_int(axe);
Matrix4d motion = getMovingMatrix(fix_coord, angle);
camera_.apply_transform_to_world(motion);
```

2021-05-25 15:56 UTC, DimaTrushin commented on src/application.cpp
> +        if (sf::Keyboard::isKeyPressed(sf::Keyboard::Left)) {
Выдели обработку клавишь в отдельную функцию, если у тебя KeyPressEvent (или как там оно в sfml называется, я видел у кого-то, что так можно). И потом там сделай большой switch, а не линейный поиск по всем if-ам. Потому что ты во все if-ы каждый раз заходишь.

2021-05-25 15:56 UTC, DimaTrushin commented on src/application.cpp
> +    for (std::unique_ptr<SurfaceObject>& object : world_) {
здесь можно писать 
for (auto& object_ptr : world_)
это даже более читаемо.

И если я правильно понимаю у тебя функция утроена так
```cpp
for (auto& object_ptr : world_)
  move_object(object_ptr);
```

2021-05-25 15:56 UTC, DimaTrushin commented on src/application.cpp
> +    Matrix4d moving = Matrix4d::identity_matrix();
Здесь опять куча ручной работы. Странно, что ты не предусмотрел для подобной работы метод-конструктор.

2021-05-25 15:56 UTC, DimaTrushin commented on src/application.cpp
> +            for (auto& triangle : renderer_.clip(camera_, triangle4d)) {
Два вложенных цикла -- бан. А три... Ну вобщем надо рефакторить.

2021-05-25 15:56 UTC, DimaTrushin commented on src/application.cpp
> +        for (auto& line3d : object->lines()) {
Что этот кусок делает?

2021-05-25 15:56 UTC, DimaTrushin commented on src/application.cpp
> +    renderer_.update(window_);
Эта штука что делает? Название метода нисколько не помогает.

2021-05-25 15:56 UTC, DimaTrushin commented on src/application.cpp
> +    for (auto& object : world_) {
А тут что за работа происходит?

2021-05-25 15:56 UTC, DimaTrushin commented on src/application.h
> +    void update();
Тогда назови update_frame. Только что это в точности значит? Отрисовка сюда входит? Если да, то это тоже надо отразить в названии.

2021-05-25 15:56 UTC, DimaTrushin commented on src/camera.cpp
> +void Camera::create_transformation_matrixes() {
Методы должны идти в том же порядке, в каком они идут в хедере.

2021-05-25 15:56 UTC, DimaTrushin commented on src/camera.h
> +    Camera();
Я не нашел имплементацию дефолтного конструктора. Судя по всему ошибки линковки нет, потому что ты нигде не строишь дефолтную камеру. Если у тебя дефолтная имплементация, то пишут так
Camera() = default;

2021-05-25 15:56 UTC, DimaTrushin commented on src/camera.cpp
> +double Camera::get_clipping_plane() const {
плохое название, ты возвращаешь double, а говоришь clipping_plane. Видимо "расстояние" до нее возвращаешь.

2021-05-25 15:56 UTC, DimaTrushin commented on src/camera.cpp
> +Point4d Camera::transform_point(Point4d p) const {
тут не совсем понятно transform куда. Видимо в куб.

2021-05-25 15:56 UTC, DimaTrushin commented on src/camera.h
> +        \brief Получение третьей координаты точки
в каком базисе?

2021-05-25 15:56 UTC, DimaTrushin commented on src/camera.h
> +        \brief Получение видоизмененных 2д-коортинат точки
что значит видоизмененных?

2021-05-25 15:56 UTC, DimaTrushin commented on src/camera.h
> +    const double kScreenHeight_;
почему константы не имеют дефолтных значений и не являются constexpr и не статические? Если они привязаны к данному объекту, то почему константы? Их что нельзя менять?

2021-05-25 15:56 UTC, DimaTrushin commented on src/camera.h
> +    Point4d position_{0, 0, 0};
Это точка угла экрана, центра экрана, фокусная точка? Какая? Кстати, а 4-ая коодрината по дефолту создается 1?

2021-05-25 15:56 UTC, DimaTrushin commented on src/camera.h
> +    Matrix4d transform_space_to_screen_ = Matrix4d::identity_matrix();
Откуда столько много матриц? Выглядит как дублирование данных. Это чисто для предрассчета, чтобы не вычислять потом эти данные по нескольку раз?

2021-05-25 15:56 UTC, DimaTrushin commented on src/camera.h
> +    constexpr static Point4d kLeftPoint_{-200, -200, 300};
Если публичные константы, то _ не надо в конце. А то к ним будет неловко обращаться. Пользователь подумает, что нечайно использует детали имплементации.

2021-05-25 15:56 UTC, DimaTrushin commented on src/chair.h
> +    ~Chair() = default;
Раз так работает. То надо просто убрать эту строчку. Компилятор сам ее сгенерирует и не пометит, что ты объявил деструктор. Это сильно лучше будет. Ибо сейчас у тебя нет move конструкторов. И я бы не надеялся на дефолтные копи версии.

2021-05-25 15:56 UTC, DimaTrushin commented on src/cube.cpp
> +
Лучше не буду спрашивать, почему порядок именно такой. Эта картинка вообще правда?

2021-05-25 15:56 UTC, DimaTrushin commented on src/cube.h
> +    ~Cube() = default;
убрать

2021-05-25 15:56 UTC, DimaTrushin commented on src/cube.h
> +    static constexpr Vector4d start = Vector4d(0, 0, 400);
_

2021-05-25 15:56 UTC, DimaTrushin commented on src/line.h
> +    double length_;
Не делай публичными данные у классов с конструкторами. Конструкторы означают инварианты. А публичные данные -- их отсутствие. Кроме того, тогда надо называть данные без _ в конце.

2021-05-25 15:56 UTC, DimaTrushin commented on src/line.h
> +    Point4d start_, finish_;
Не объявляй в одной строчке данные. И закрой их.

2021-05-25 15:56 UTC, DimaTrushin commented on src/line.cpp
> +Line2d::Line2d(double length): length_(length) {}
А другие значения мусор из памяти? Например angle у тебя будет мусором после такого конструктора. А offset какой по дефолту будет?

2021-05-25 15:56 UTC, DimaTrushin commented on src/line.h
> +    sf::Vector2f offset_;
А что это вообще такое?

2021-05-25 15:56 UTC, DimaTrushin commented on src/log.h
> +
Будем считать, что я этого не видел.

2021-05-25 16:52 UTC, DimaTrushin requested changes
Вот тебе добавка. Больше видеть не могу. Измени все что релевантно по аналогии.

2021-05-25 16:52 UTC, DimaTrushin commented on src/matrix.h
> +    Matrix() {
В начале конструкторы.

2021-05-25 16:52 UTC, DimaTrushin commented on src/matrix.h
> +    Matrix(std::array<double, 4>&& data): data_{{std::forward<std::array<double, 4>>(data)}} {}
forward из std::array не имеет смысла. std::forward -- это либо каст к lvalue либо каст к rvalue. В любом случае произойдет копирование локальной части объекта. А у std::array все находится в локальной части. Так что это все не имеет значения. У тебя всегда будет копирование. Но вот что можно было бы сделать -- написать
Matrix(const std::array<double, 4>& data)
Потому что сейчас у тебя именованные массивы нельзя подставлять в конструктор.

2021-05-25 16:52 UTC, DimaTrushin commented on src/matrix.h
> +    Matrix(const std::vector<std::vector<double>>& initial) {
Зачем такое огромное количество разных конструкторов? Ты ими точно пользуешься. Особенно вот этим от вектора векторов?

2021-05-25 16:52 UTC, DimaTrushin commented on src/matrix.h
> +    void modification_multiply(size_t i, double k) noexcept {
Если я правильно понял, ты хочешь текущую строку умножить на k, если так, то лучше так
```cpp
Matrix& multiply_row(size_t row, double multiplier) {
  ...
  return *this;
}
```
Тогда и название будет хорошим и чейнить можно такие вещи, например
```cpp
Matrix a;
a.multiply_row(3, 5).multiply_column(4,2);
```

2021-05-25 16:52 UTC, DimaTrushin commented on src/matrix.h
> +    void modification_swap(size_t i, size_t j) noexcept {
Это называется swap_rows

2021-05-25 16:52 UTC, DimaTrushin commented on src/matrix.h
> +    bool operator == (const Matrix& other) const noexcept {
Лучше бинарные операторы делать friend методами. Тогда они позволят конвертацию обоих аргументов. А так у тебя только по второму. Я бы написал
friend bool operator==(const Matrix& first, const Matrix& second) {...}
Тогда будет конвертация по обоим аргументам работать.

2021-05-25 16:52 UTC, DimaTrushin commented on src/matrix.h
> +    Matrix operator + (const Matrix& other) const noexcept {
сделай 
friend Matrix operator+(const Matrix& first, const Matrix& second) noexcept {...}
тогда конвертация по обоим аргументам работать будет.

2021-05-25 16:52 UTC, DimaTrushin commented on src/matrix.h
> +            tmp[i] = vector.x * (*this)(i, 0) + vector.y * (*this)(i, 1) + vector.z * (*this)(i, 2) + vector.w * (*this)(i, 3);
Сделай у Vector4d обращение к координатам по номерам и тогда не надо будет вводить лишний временный объект tmp. У тебя рассинхрон интерфейсов.

2021-05-25 16:52 UTC, DimaTrushin commented on src/matrix.h
> +        return result;
Не ужели у тебя среди миллиона конструкторов нет того, который по std::array создает вектор?

2021-05-25 16:52 UTC, DimaTrushin commented on src/matrix.h
> +    Point4d row(size_t idx) const noexcept {
А почему строка в виде Point4d, а не Vector4d?

2021-05-25 16:52 UTC, DimaTrushin commented on src/matrix.h
> +        assert(M == 2);
Это делается через static_assert. Не надо проверять параметры известные в compile time через обычный assert.

2021-05-25 16:52 UTC, DimaTrushin commented on src/matrix.h
> +        assert(_N == N);
Либо static_assert либо enable_if в параметрах шаблона.

2021-05-25 16:52 UTC, DimaTrushin commented on src/matrix.h
> +                if (copy(i, j) != 0) {
Кстати. Не самый устойчивый метод. Уж лучше искать максимальный по модулю элемент.

2021-05-25 16:52 UTC, DimaTrushin commented on src/matrix.h
> +        assert(_N == N);
Длиннова-та функция. Неужели нельзя было разделить хтя бы на прямой и обратный ход?

2021-05-25 16:52 UTC, DimaTrushin commented on src/matrix.h
> +    void gaussian(Matrix<_N, _M>& second) {
Во-первых, по названию не понятно что происходит.
Во-вторых, не ясна роль второго параметра.
В-третьих, я все таки увидел, что он у тебя не константная ссылка. А это плохо. Это выходной параметр, который ты меняешь и вызывающий этого не видит. Выходные параметры надо передавать по указателю, а входные по константной ссылке.

2021-05-25 16:52 UTC, DimaTrushin commented on src/renderer.h
> +    const unsigned int screen_width_, screen_height_;
почему константы? Если это параметры класса, то не константы. Если это константы класса, то constexpr и static.

2021-05-25 16:52 UTC, DimaTrushin commented on src/renderer.h
> +class Screen;
Это лишнее.

2021-05-25 16:52 UTC, DimaTrushin commented on src/renderer.h
> +class Camera;
Раз ты заинклудил camera.h, то это тоже лишнее.

2021-05-25 16:52 UTC, DimaTrushin commented on src/renderer.h
> +
Очень много методов у Renderer-а. Для чего ты его используешь? неужели все эти функции ты используешь снаружи? Я вижу это так. что ты делаешь один вызов рендерера для получения кратинки, а потом скармливаешь картинку другому объекту, что умеет рисовать пользователю на экран.
Но судя по всему у тебя Renderer должен сам уметь отрисовывать (судя по методу update).

В общем, пока мутно все. Я бы закрыл как можно больше методов рендерера в приват и посмотрел, что реально от него надо.

2021-05-25 16:52 UTC, DimaTrushin commented on src/renderer.cpp
> +    bool is_degenerate(Triangle2d triangle) {
Почему этого метода нет там, где объявлены треугольники? Выглядит как метод для треугольника.

2021-05-25 16:52 UTC, DimaTrushin commented on src/renderer.cpp
> +    screen_width_(screen_width),
Выглядит так, что screen_ уже хранит  эти данные. Почему ты их тут еще дополнительно хранишь? Если надо, то сделай методы доступа к размерам экрана внутри screen_. Чтобы тут не дублировать информацию. Если надо сделай эти методы приватными.

2021-05-25 16:52 UTC, DimaTrushin commented on src/renderer.cpp
> +    draw(screen_.get_picture(), window);
Странно, что get_picture() не возвращает структурированный объект, а вместо него какой-то вектор из вершин. Как видно по сигнатуре ниже.

2021-05-25 16:52 UTC, DimaTrushin commented on src/renderer.cpp
> +    const sf::Vertex* ptr = &data[0];
Эта переменная не нужна. можно ниже сразу написать data->data() вместо этой вот лабуды.

2021-05-25 16:52 UTC, DimaTrushin commented on src/renderer.cpp
> +Matrix<2, 1> Renderer::get_coords(int x, int y, Matrix<2, 2>& basis, sf::Vector2f& left_point) const {
Этот метод явно должен быть в закрытом интерфейсе рендерера. Если он и использует этот метод для своих целей, то уж никак не его задача этот метод предоставлять его пользователям.

2021-05-25 16:52 UTC, DimaTrushin commented on src/renderer.cpp
> +void Renderer::draw(const Camera& camera, const Triangle4d& triangle4d) {
Рефактор. Слишком длинный метод.

2021-05-25 16:52 UTC, DimaTrushin commented on src/renderer.cpp
> +    Triangle2d triangle2d(camera.project_point(triangle4d.a),
Сделай метод project_triangle. Иначе это нарушение уровня абстракции. Ты хочешь сказать "спроецируй треугольник", а говоришь "спроецируй первую координату треугольника, спроецируй вторую координату треугольника, спроецируй третью координату треугольника, потом возьми три проекции и собери из них двумерный треугольник". Это явно нарушение уровня абстракции, ты тут делаешь более низкоуровневую работу, чем нужно.

2021-05-25 16:52 UTC, DimaTrushin commented on src/renderer.cpp
> +    std::array<int, 3> order = triangle2d.get_order();
Разбей код ниже на подфункции, чтобы было понятно, что за дичь ты тут делаешь.

2021-05-25 16:52 UTC, DimaTrushin commented on src/renderer.cpp
> +    if (A.z <= z_plane && B.z <= z_plane) {
Условия под if-ом запихни в функцию с нормальным именем. Что ты тут проверяешь? Что точки одновременно перед передней поверхностью? Как это понять из названия z_plane?

2021-05-25 16:52 UTC, DimaTrushin commented on src/renderer.cpp
> +    if (A.z < z_plane || B.z < z_plane) {
А тут что происходит?

2021-05-25 16:52 UTC, DimaTrushin commented on src/renderer.cpp
> +    sf::RectangleShape rectangle(sf::Vector2f(line.length_, line.kWidth));
Строчки 93 -- 96. Тут какая-то хрень творится. Ты по сути хочешь в одной строчке создать rectangle. Но создаешь его в 93 частично, а потом правишь. Почему не сделать сразу конструирование как надо в одной строчке. Кроме того, у тебя перед вызовом конструктора конструируется Vector2f. Это явное нарушение уровня абстракции. Ну и на последовк почему у length усть _, а у kWidth ее нет?

2021-05-25 16:52 UTC, DimaTrushin commented on src/renderer.cpp
> +std::vector<Triangle4d> Renderer::clip(const Camera& camera, const Triangle4d& triangle) const {
Слишком длинная функция. Рефактор.

2021-05-25 16:52 UTC, DimaTrushin commented on src/screen.cpp
> +                data.push_back(sf::Vertex(sf::Vector2f(i, j), color_(i, j)));
Если ты создаешь Vertex по данным, то лучше emplace_back вот так
```cpp
data.emplace_back(sf::Vector2f(i, j), color_(i, j));
```
Тогда у тебя соответствующий вектор создастся inplace по передаваемым аргументам. Не будет лишних копий.

2021-05-25 16:52 UTC, DimaTrushin commented on src/screen.cpp
> +            if (z_value_(i, j) < max_z_value_) {
убить бы за три вложенных скоупа.

2021-05-25 16:52 UTC, DimaTrushin commented on src/screen.cpp
> +std::vector<sf::Vertex> Screen::get_picture() {
Почему этот метод не константный и возвращает неструктурированный объект? Да еще и by value? Выглядит так, что у тебя должен быть внутри буфер экрана и ты хочешь просто вернуть ссылку на него. Что тут происходит?

2021-05-25 16:52 UTC, DimaTrushin commented on src/screen.h
> +    size_t screen_width_;
Судя по всему у тебя z_value_ и color_ хранят эти размеры и тебе надо лишь их согласованность. Нафига ты их тут хранишь? Сделай метод доступа и проверяй assert-ом согласованность.

2021-05-25 16:52 UTC, DimaTrushin commented on src/screen.h
> +    double max_z_value_;
Почему screen знает про max_z_value_? Откуда у него такие супер знания? Этого тут быть не должно. Я еще понимаю в z-buffer положить это значение по дефолту.

2021-05-25 16:52 UTC, DimaTrushin commented on src/screen.cpp
> +    if (x < 0 || y < 0 || x >= screen_height_ || y >= screen_width_ ||
Условие.

2021-05-25 16:52 UTC, DimaTrushin commented on src/screen.cpp
> +    for (int i = 0; i < screen_width_; i++) {
Это ошибка уровня абстракции. PixelScreen должен предоставить метод set_all_pixels(...);  и тут ты вызываешь в двух строчках эти методы. А цикл будет линейным внутри каждого из этих методов (потому что там линейный буфер внутри). Вот и нет ненужного двойного цикла. Ты просто думаешь имплементацией, потому делаешь дурацкие циклы.

2021-05-25 16:52 UTC, DimaTrushin commented on src/screen.cpp
> +    for (int i = 0; i  < screen_width_; i++) {
Как я и писал у тебя должен быть метод инициализации буфера одним значением и это надо убрать, а буфер инициализировать в списке инициализации.

2021-05-25 16:52 UTC, DimaTrushin commented on src/triangle.cpp
> +    if (order[0] == 0) {
Это должен быть набор switch-ей, а не линейный набор if_ов.
Но даже так получается не сильно радужно. Вот что ты тут делаешь в этом методе -- большой вопрос.

2021-05-25 16:52 UTC, DimaTrushin commented on src/triangle.cpp
> +void Triangle4d::assign_points(std::array<int, 3> order, Point4d& a, Point4d& b, Point4d& c) const {
по имени метода не понятно, что он делает.

2021-05-25 16:52 UTC, DimaTrushin commented on test/test.cpp
> +    application.add_object(std::make_unique<app::Cube>());
Вообще выглядит странно, что ты в application добавляешь объект, а не в мир.

2021-05-25 16:52 UTC, DimaTrushin commented on src/world.h
> +    std::vector<std::unique_ptr<SurfaceObject>>::iterator begin();
Чтобы не писать такую колбасу люди придумали using-ги.
using ObjectHolder = std::unique_ptr<SurfaceObject>;
using ObjectContainer = std::vector<ObjectHolder>;
using iterator = ObjectContainer::iterator;
using const_iterator = ObjectContainer::const_iterator;

2021-05-25 16:52 UTC, DimaTrushin commented on src/world.h
> +    std::vector<std::unique_ptr<SurfaceObject>> objects_;
А почему не std::list? У тебя все равно в векторе хранятся unique_ptr и все объекты по памяти разбросаны как брызги слюны по кухне. Ты просто платишь за реаллокацию вектора и не получаешь бонуса от непрерывной памяти.

2021-05-25 16:52 UTC, DimaTrushin commented on src/world.h
> +    void update();
А это что за метод?

2021-05-25 16:52 UTC, DimaTrushin commented on src/world.cpp
> +void World::update() {}
Так и думал, что ни о чем =)

2021-05-25 16:52 UTC, DimaTrushin commented on src/world.cpp
> +    objects_.emplace_back(std::move(t));
тут, кстати, нет разницы между emplace_back и push_back.

2021-05-25 16:52 UTC, DimaTrushin commented on src/surface_object.h
> +private:
Непостоянство, у тебя то приватные данные в начале, то в конце. Убрать все в конец.

2021-05-25 16:52 UTC, DimaTrushin commented on src/surface_object.cpp
> +    WireObject(points, edges) {}
Вот это дорогого стоит. У тебя передаются векторы (потенциально из миллиона объектов) и ты их тут в виде копии передаешь в базовый конструктор! Надо так
```cpp
 WireObject(std::move(points), std::move(edges))
```
Запомни, если конструктор принимает аргументы by value, то он должен мувнуть их в данные или в базовые конструкторы.

2021-05-25 16:52 UTC, DimaTrushin commented on src/surface_object.cpp
> +    WireObject(points, edges), triangles_(triangles) {}
Аналогичное замечание.

2021-05-25 23:47 UTC, KiK0S commented on src/application.cpp
> +        for (auto& line3d : object->lines()) {
вообще, рисует линии, потому что sfml отдельно это умеет делать. но я думаю, что откажусь от этого, так не видно, как работает z-буфер

2021-05-25 23:48 UTC, KiK0S commented on src/application.cpp
> +    for (auto& object : world_) {
тут как раз должны были отображаться линии. а вот выше они были лишними

2021-05-27 23:01 UTC, KiK0S commented on src/camera.h
> +    Point4d position_{0, 0, 0};
по дефолту 1, да

2021-05-27 23:02 UTC, KiK0S commented on src/camera.h
> +    constexpr static Point4d kLeftPoint_{-200, -200, 300};
непубличные

2021-05-27 23:04 UTC, KiK0S commented on src/matrix.h
> +    Matrix() {
не совсем, темплейтный конструктор требует сразу определение, а там используется data_

2021-05-28 10:20 UTC, KiK0S commented on src/camera.h
> +    Matrix4d transform_space_to_screen_ = Matrix4d::identity_matrix();
Да, для предрассчета.

2021-05-28 10:20 UTC, KiK0S commented on src/cube.cpp
> +
Порядок просто какой-то, картинка правдива

2021-05-28 10:37 UTC, KiK0S commented on src/matrix.h
> +    Matrix() {
настолько в начале, насколько возможно

2021-05-28 10:38 UTC, KiK0S commented on src/matrix.h
> +    Matrix(const std::vector<std::vector<double>>& initial) {
какие-то поудалял

2021-05-29 21:29 UTC, KiK0S commented on src/application.cpp
> +    Matrix4d moving = Matrix4d::identity_matrix();
Теперь сделал статический метод

2021-05-30 17:38 UTC, KiK0S commented on src/renderer.h
> +
я так отрефакторил, что теперь там будет типа два.

2021-06-04 00:51 UTC, KiK0S commented on src/surface_object.h
> +private:
Ну так не работает компиляция по понятным причинам, у меня триплет используется

2021-06-22 11:36 UTC, merged